version: '3'

services:
  weekly-mysql:
    image: mysql:5.7
    container_name: 'weekly_mysql'
    ports:
      - 3306:3306
    restart: always
    volumes:
      - /data/weekly-mysql/data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: "246810"
      TZ: "Asia/Shanghai"
    networks:
      - elk

  weekly-server:
    build: ../beego-server/
    container_name: 'weekly_server'
    ports:
      - 8080:8080
    volumes:
      - /data/weekly-server/log:/go/logs
    environment:
      TZ: "Asia/Shanghai"
    restart: always
    networks:
      - elk

  weekly-web:
    image: nginx
    ports:
      - 8081:80
    container_name: 'weekly_web'
    restart: always
    volumes:
      - ../antd-ui/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /data/weekly-web/log:/var/log/nginx
    environment:
      TZ: "Asia/Shanghai"
    networks:
      - elk

networks:
  elk:
    driver: bridge